version: '3.8'
services:
  frontend:      
    build:
      context: ../../client
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../../client/build:/usr/share/nginx/html
      # - ../../:/etc/nginx

