version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=1,
    ports:
      - '3307:3306'
    expose:
      - 3306


  backend:      
    build:
      context: ../../server
      dockerfile: Dockerfile
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      # - DB_HOST=host.docker.internal
    ports:
      - 5000:5000
    # expose:
    #   - 5000
    depends_on:
      - db


  frontend:      
    build:
      context: ../../client
      dockerfile: Dockerfile
    # environment:
      # - DB_PORT=5001
      # - DB_HOST=db
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    depends_on:
      - backend

